# Site settings
title: "Yash Sharma"
description: "Engineer in Hospital"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yash Sharma"
resume_title:                   "Changing Healthcare one bit at a time"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ys5hd@virginia.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "434-249-4526"
resume_contact_address:         "1800 Jefferson Park Ave"

resume_header_contact_info:     "1800 Jefferson Park Ave, Charlottesville • 434-249-4526 • ys5hd@virginia.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a Research Assistant at <a href='https://gastrodatasciencelab.org'>Gastroenterology Data Science Lab</a> at the University of Virginia, working under the guidance of <a href='https://research.med.virginia.edu/chrc/key-investigators/sana-syed-md-ms/'>Dr. Sana Syed</a> and <a href='https://engineering.virginia.edu/faculty/donald-e-brown-phd'>Dr. Donald E. Brown</a> and collaborating with a team of researchers and doctors. My research focuses on developing end-to-end interpretable deep learning architecture for gastrointestinal disease classification and multi-modal modeling integrating transcriptomics data with biopsy images. The need for interpretable modeling and the lack of supervision in medical imaging are exciting problem, and I intend to contribute in this direction. </p>
<p> I have over three years of industrial experience as a Data Scientist with <a href='https://www.zs.com/'>ZS Associates</a> (Consulting firm) and <a href='https://www.freshworks.com/'>Freshworks</a> (Software-as-a-service product firm). 
At ZS, I was part of the Advanced Data Science group working on developing ML-based solutions for top pharmaceutical firms like Amgen, Pfizer, Merck, etc. 
Exposure to problems in the drug development and manufacturing phase made me realize the much-needed requirement of bringing computational advancement to the medical field. My time at Freshworks helped me understand the challenges of scaling an ML idea and putting it into production. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_publication:     true
resume_section_interests:       false

# Navigation
show_navigation: true
show_introduction_nav_link: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/YashSharma"
  resume_twitter_url:           "https://twitter.com/yashsharma0906"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yashsharma0906/"
  resume_instagram_url:         "https://www.instagram.com/theyashtray/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
